# See https://github.com/kubernetes-sigs/prow/blob/main/pkg/plugins/plugin-config-documented.yaml
# owners:
#   # By default, prow will use github org membership as the list of who is allowed to
#   # /lgtm PRs.  This configuration setting tells it to use the OWNERS file only and
#   # can be applied to a specific repo or entire github org.
#   skip_collaborators:
#   - "suse"
plugins:
  ldevulder/prow-gh-test:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - heart
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - pony
    - retitle
    - shrug
    - size
    - transfer-issue
    - trigger
    - verify-owners
    - wip
    - yuks
    - require-matching-label
    - override
    - config-updater
#  suse/elemental-ci:
#    plugins:
#    - config-updater

approve:
- repos:
  - ldevulder/prow-gh-test
  # RequireSelfApproval requires PR authors to explicitly approve their PRs.
  # Otherwise the plugin assumes the author of the PR approves the changes in the PR.
  require_self_approval: true

  # A /lgtm from a single approver should not allow a PR to merge.
  lgtm_acts_as_approve: false

# blunderbuss:
#   max_request_count: 2
#   use_status_availability: true

config_updater:
  maps:
    # Update the config configmap whenever config.yaml changes
    prow/config/config.yaml:
      name: config
    # Update the plugins configmap whenever plugins.yaml changes
    prow/config/plugins.yaml:
      name: plugins
#    # Update the label-config configmap whenever labels.yaml changes
#    prow/config/labels.yaml:
#      name: label-config
#    # Update the job-config configmap whenever anything under jobs changes
#    prow/config/jobs/**/*.yaml:
#      name: job-config

# triggers:
# - repos:
#   - metal3-io
#   # Enable prow to trigger GitHub workflows.
#   trigger_github_workflows: true
